### ISSUE TITLE
Encontre posibles formatos para publicacion del hacelo-vos-mismo

### ISSUE THREAD

**Issue by sebalander** [ale-mendez/hacelo-vos-mismo#4]
en una tarea no relacionada estaba mirando los tempates de repositorio que ofrece Gitlab. Aparecieron estos:

![Screenshot from 2022-03-16 10-08-50](https://user-images.githubusercontent.com/7595088/158611308-93136f38-c613-4144-9361-d30f3f6b1dc1.png)

No se que es "gitlab pages" pero me da curiosidad y capaz este relacionado con la publicacion que queremos hacer.

**Comment by AlbertoImg** [comment]
Hugo markdown https://gohugo.io/content-management/formats/

**Comment by sebalander** [comment]
Creo que este issue se puede cerrar, nos quedamos con hugo por ahora, no?

**Comment by kakila** [comment]
Ok
